config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :bulletins do
    resources :posts
  end

  resources :posts do
    resources :comments, only:[:create, :destroy]
  end

end

app/models/bulletin.rb
class Bulletin < ActiveRecord::Base
	has_many :posts, dependent: :destroy
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post

  validates :body, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :bulletin
	has_many :comments, dependent: :destroy
	acts_as_taggable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bulletins_controller.rb
class BulletinsController < ApplicationController
  before_action :set_bulletin, only: [:show, :edit, :update, :destroy]

  # GET /bulletins
  # GET /bulletins.json
  def index
    @bulletins = Bulletin.all
  end

  # GET /bulletins/1
  # GET /bulletins/1.json
  def show
  end

  # GET /bulletins/new
  def new
    @bulletin = Bulletin.new
  end

  # GET /bulletins/1/edit
  def edit
  end

  # POST /bulletins
  # POST /bulletins.json
  def create
    @bulletin = Bulletin.new(bulletin_params)

    respond_to do |format|
      if @bulletin.save
        format.html { redirect_to @bulletin, notice: 'Bulletin was successfully created.' }
        format.json { render :show, status: :created, location: @bulletin }
      else
        format.html { render :new }
        format.json { render json: @bulletin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bulletins/1
  # PATCH/PUT /bulletins/1.json
  def update
    respond_to do |format|
      if @bulletin.update(bulletin_params)
        format.html { redirect_to @bulletin, notice: 'Bulletin was successfully updated.' }
        format.json { render :show, status: :ok, location: @bulletin }
      else
        format.html { render :edit }
        format.json { render json: @bulletin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bulletins/1
  # DELETE /bulletins/1.json
  def destroy
    @bulletin.destroy
    respond_to do |format|
      format.html { redirect_to bulletins_url, notice: 'Bulletin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bulletin
      @bulletin = Bulletin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bulletin_params
      params.require(:bulletin).permit(:title, :description)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post
  before_action :set_comment, only: :destroy

  def create
    @comment = @post.comments.new(comment_params)
    @comment.save
  end

  def destroy
    @comment.destroy
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def set_comment
    @comment = @post.comments.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_bulletin
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = @bulletin.posts.all
  end

  def show
  end

  def new
    @post = @bulletin.posts.new
  end

  def edit
  end

  def create
    @post = @bulletin.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to [@post.bulletin, @post], notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to [@post.bulletin, @post], notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to bulletin_posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_bulletin
      @bulletin = Bulletin.find(params[:bulletin_id])
    end

    def set_post
      @post = @bulletin.posts.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :content, :tag_list)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def tag_icons(tag_list)
 	 tag_list.map do | tag |
    "<a href='/posts?tag=#{CGI::escape(tag)}' class='tag'>#{tag}</a>"
  end.join(', ').html_safe
	end
end

app/helpers/bulletins_helper.rb
module BulletinsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bulletins/_form.html.erb
<%= simple_form_for(@bulletin) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/bulletins/edit.html.erb
<h1>Editing Bulletin</h1>

<%= render 'form' %>

<%= link_to 'Show', @bulletin %> |
<%= link_to 'Back', bulletins_path %>

app/views/bulletins/index.html.erb
<h2>Bulletins</h2>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Data actions</th>
    </tr>
  </thead>

  <tbody>
    <% @bulletins.each do |bulletin| %>
      <tr>
        <td><%= bulletin.title %></td>
        <td><%= bulletin.description %></td>
        <td>
          <%= link_to 'Show', bulletin, class: 'btn btn-default' %>
          <%= link_to 'Edit', edit_bulletin_path(bulletin), class: 'btn btn-default' %>
          <%= link_to 'Destroy', bulletin, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bulletin', new_bulletin_path, class: 'btn btn-default' %>

app/views/bulletins/new.html.erb
<h1>New Bulletin</h1>

<%= render 'form' %>

<%= link_to 'Back', bulletins_path %>

app/views/bulletins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @bulletin.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @bulletin.description %>
</p>

<%= link_to 'Edit', edit_bulletin_path(@bulletin) %> |
<%= link_to 'Back', bulletins_path %>

app/views/comments/_comment.html.erb
<li id="comment_<%=comment.id %>">
  <%= comment.body %>,
  <%= time_ago_in_words(comment.created_at) %> ago
  <%= link_to fa_icon("times-circle-o"), [comment.post, comment], method: :delete, remote: true, data: { confirm: "Are you sure?" } %>
</li>

app/views/comments/_comments.html.erb
<div class="comments">
  <div class="comment_header">
    <h2>Comments:</h2>
  </div>
  <div class="comments_list">
    <%= render "comments/list" %>
  </div>
  <div class='comments_form'>
    <%= render "comments/form" %>
  </div>
</div>

app/views/comments/_form.html.erb
<% comment = @post.comments.new %>
<div id="comments_form_<%=@post.id%>">
<%= simple_form_for([@post, comment], remote: true ) do | f | %>
  <div class='form-inputs'>
    <%= f.input :body, label: false, placeholder: 'Add a comment.',  input_html: { rows: 5 } %>
  </div>
  <div class='form-actions'>
    <%= f.button :submit %>
  </div>
<% end %>
</div>

app/views/comments/_list.html.erb
<ul id="comments_list_<%=@post.id%>">
<% if @post.comments.size > 0 %>
  <%= render @post.comments %>
<% else %>
  <li>
    No comments
  </li>
<% end %>
</ul>

app/views/comments/create.js.erb
<% if @comment.errors.size == 0 %>
  $('<%=j render @comment %>').appendTo($("#comments_list_<%=@post.id %>")).hide().fadeIn('fast');
  $("#comments_form_<%=@post.id %> form")[0].reset();
<% else %>
  alert("Please submit after commenting...");
<% end %>

app/views/comments/destroy.js.erb
$("#comment_<%=@comment.id %>").slideUp('fast');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blind Book</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <!-- Fixed navbar -->
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to raw("Blind Book"), root_path, class:'navbar-brand' %>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class>
            <%= link_to raw("<small>책 리스트</small>"), bulletin_posts_path(1), class:'navbar-brand' %>
            <%= link_to raw("<small>참여방법</small>"), bulletin_posts_path(2), class:'navbar-brand' %>
            <%= link_to raw("<small>마이페이지</small>"), bulletin_posts_path(2), class:'navbar-brand' %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container">

      <%= yield %>

    </div> <!-- /container -->
</body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for([@bulletin, @post]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :content %>
    <%= f.input :tag_list, placeholder: '하나 이상의 태그는 콤마(,)로 구분하여 입력하세요.' %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', [@post.bulletin, @post], class: 'btn btn-default' %>
<%= link_to 'Back', bulletin_posts_path, class: 'btn btn-default' %>

app/views/posts/index.html.erb
<h2>Listing posts</h2>

<table class="table">
  <thead>
    <tr>
      <th>No.</th>
      <th>Status</th>
      <th>Data actions</th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td>
          <%= link_to 'Show', [post.bulletin, post], class:'btn btn-default' %>
          <%= link_to 'Edit', edit_bulletin_post_path(post.bulletin, post), class:'btn btn-default' %>
          <%= link_to 'Destroy', [post.bulletin, post], method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-default' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_bulletin_post_path, class: 'btn btn-default' %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', bulletin_posts_path, class: 'btn btn-default' %>

app/views/posts/show.html.erb
<h2>Post Preview</h2>

<p>
  <strong>No.:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Status:</strong>
  <%= @post.content %>
</p>

<tr>
  <th><strong>Tag list</strong></th>
  <td><%= tag_icons @post.tag_list %></td>
</tr>

<%= render "comments/comments" %>

<hr>

<%= link_to 'Edit', edit_bulletin_post_path(@post.bulletin, @post), class: 'btn btn-default' %>
<%= link_to 'Back', bulletin_posts_path, class: 'btn btn-default' %>

app/views/welcome/index.html.erb
<h1>Have a blind date with a book</h1>
<p>여행 중 프랑크푸르트 공항에서 서점에 들렀는데, 아주 재밌는 이벤트가 진행 중이더라고요^^</p>

<p>블라인드 데이트를 제안하는데, 그건 다름아닌 책과의 데이트입니다.!</p>

<p>손으로 투박하게 직접 포장된 책이 있는데, 어떤 책인지는 알 수 없고요, 대신에 포장지에 책과 관련된 아주 간단한 키워드와 설명들이 쓰여 있습니다:) 책의 장르와 분위기 같은 걸 알려주는 힌트들도 등장하구요^^</p>

<p>사실 우리는 책과 친해지고 싶다가도, 금방 지루해지곤 하는데요, 이런 방식으로 좀 더 색다르고 설레는 방식으로 책을 교환해서 읽어보면 어떨까요?</p>

<p>자기가 읽은 책 중에 인상깊었던 책, 남들은 잘 모르지만 꼭 한번 누군가에게 추천해주고 싶은 책들로 오컬 서가를 만드는 거예요!</p>

<p>직접 포장한 투박한 모양으로, 누군가에게 읽히게 될지 모를 기대를 안고서 말이죠. 이렇게 책 교환해서 읽으면 혹시 아나요?</p>

<p>우연히 만나게 된 blind date with a book이 당신의 인생을 송두리째 바꾸어놓을지도 모릅니다!</p>

<br/>

<%= link_to "책 리스트", bulletin_posts_path(1), class:'btn btn-default' %>